### ISSUE TITLE
Confusing UX for Adding Server URL and Auth Token in Matomo

### ISSUE THREAD

**Issue by danielmcclure** [matomo-org/looker-studio-connector#13]
## Description

There is a potential issue with the user experience (UX) when users are asked to submit a username to connect with Looker Studio but need to submit their Matomo server URL instead. 

![add-data-credentials](https://github.com/matomo-org/looker-studio-connector/assets/2772782/b6135c44-d163-4c59-8f00-82565e0ee0f9)

### Current Behaviour

- The process to add a server URL and an authentication token is potentially confusing.
- The connector description currently links to a top-level topic in the Knowledge Base (KB).

### Expected Behaviour

- The process to add a server URL and an authentication token should be clear and intuitive.
- Users should ideally be able to complete these steps without requiring additional guides or extensive help.

## Suggested Solution

To improve the UX and make the process more user-friendly, it is proposed that:

- The placeholder text for the user input field is updated from "Username" to "Matomo URL" if possible.
- The connector description text could be updated from "Connect to Matomo Cloud instances or self-hosted instances using just a Matomo Auth Token." to "Connect to Matomo Cloud instances or self-hosted instances using just **your Matomo URL and** a Matomo Auth Token." 
- The connector description should link directly to a **dedicated connection FAQ** specifically tailored to guide users through the process of adding a server URL and an authentication token. The FAQ should provide step-by-step instructions, troubleshooting tips, and clarify common questions or issues specific to the connection process.

## Benefits
- **Increased Clarity:** Stating that a URL is required inline would help users know what details are required by the form. 
- **Reduced Confusion:** Clarifying in the description may enable users to infer the required details without searching externally. 
- **Improved User Experience:** Directing users to a dedicated FAQ can help alleviate confusion and reduce the number of steps required to find a solution. 

## Conclusion

Improving the user experience for adding a server URL and an authentication token is crucial for onboarding to the tool. By clarifying the required connection details and linking to a dedicated connection FAQ, we can enhance the overall usability of the Matomo Connector for Looker Studio and reduce the number of steps for users that get stuck.

**Comment by diosmosis** [comment]
Hi @danielmcclure, thanks for bringing this up, we also noticed this and tried to fix it while developing it. Unfortunately it's not something we can change, this part of the UX is entirely controlled by Looker Studio. Connectors can't change the placeholders or the learn more link. Not at the moment anyway.
