### ISSUE TITLE
Confusing progression instructions when adding data from connected instance.

### ISSUE THREAD

**Issue by danielmcclure** [matomo-org/looker-studio-connector#22]
When adding data from an already connected Matomo instance, the form window still says 'Click "CONNECT to continue.' even though the correct action is to click 'Add' at the bottom right on the window.

![add-data](https://github.com/matomo-org/looker-studio-connector/assets/2772782/37cc6e19-61af-436e-b5e1-c1cbb95fd199)

This message is also shown when editing an existing connection and the correct action would be to click 'Reconnect' at the top right of the window.

![click-reconnect](https://github.com/matomo-org/looker-studio-connector/assets/2772782/89f7c63e-3972-42c8-8136-f0574f05e0f5)

As the wording and location of the button varies, the colour of the button seems to be the only constant, although I'm not sure saying 'Click the blue button' would bring full clarity as other blue buttons may be present on the screen.

![blue-button](https://github.com/matomo-org/looker-studio-connector/assets/2772782/c9feee30-231a-4ca2-b94a-6a386270c162)

**Comment by diosmosis** [comment]
@danielmcclure This is part of the looker studio experience, we don't have the power to change this. You may want to ask on the looker studio forums or report the issue to google: https://support.google.com/looker-studio/answer/7340016?hl=en.
