### ISSUE TITLE
set default report template for users to use

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/looker-studio-connector#25]
Connectors can set a default report template by modifying the appsscript.json file:

![image](https://github.com/matomo-org/looker-studio-connector/assets/68335276/9767ec7f-3a1b-43c2-b4b3-b539982bb9c9)

However, adding it is not straightforward. In order for users to use the template successfully, they need to use a specific connector configuration. The report must be set to `API > Main Metrics` and the segment parameter must be made alterable. If users do not do this, the created report will fail to load properly.

Possible solutions to this problem:

* Add informational text letting users know they need to use specific options. Note: it is not possible for the connector to detect whether the checkbox to use the default report is selected, so we can't conditionally show this text.

* Allow not connecting to a report, giving the user the full list of dimensions and metrics Matomo supports in one data source. This will make it possible for the report to load with minimal configuration, but if a user uses an unsupported dimension/metric combination (which would be very easy to do), they will receive an error. Users will still have to allow the segment to be overridden.

Neither solution is ideal.

**Comment by wonderdevhub** [comment]
If the segment selector were not a dependency, could we include a small note or question mark tooltip next to the report that says to use "API > Main metrics" if using the default report template?

**Comment by danielmcclure** [comment]
If the segment selector were not a dependency, could we include a small note or question mark tooltip next to the report that says to use "API > Main metrics" if using the default report template?

**Comment by diosmosis** [comment]
We can add text above or below controls in the configuration screen. We can't do it conditionally based on whether the "use default report template" is selected.

**Comment by diosmosis** [comment]
Closing in favor of #27
