### ISSUE TITLE
Actions > Page URLs showing 0 for Event Conversions

### ISSUE THREAD

**Issue by SMMaEi** [matomo-org/looker-studio-connector#52]
In Matomo I set up a conversion based on an event (75% scrolled).
Using the Looker Studio Report "Actions > Page URLs" this conversion will always show 0 in Looker Studio, although conversions are recoreded in Matomo

**Comment by rcontiuk** [comment]
This is a possibly related issue. Page URL report in LK only shows few conversions, see pic below:

![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/71a53a77-6a0b-497e-801a-b795ba6efc1f)

But Matomo report shows this:

![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/71b502b8-75a2-4162-9541-3efe14dd9c75)
![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/0b6fcccb-f073-44ff-b141-36063d0dc903)
![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/c8cc9108-9b37-401c-99df-9de1ccf66cf6)


See LK settings:

![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/a1093ac3-76c3-44d8-b19b-5484c0ad4920)
![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/f8e19e84-90f2-4a57-9bc5-5c226823b3da)
![image](https://github.com/matomo-org/looker-studio-connector/assets/49957970/0f9d0eb4-1c81-487d-a25d-35d35162f152)

**Comment by diosmosis** [comment]
@SMMaEi @rcontiuk we've just deployed a fix for this issue, would you be able to tell me if it works for you?

**Comment by SMMaEi** [comment]
Thanks for the quick fix guys, much appreciated!
