### ISSUE TITLE
Total Conversions by Channel

### ISSUE THREAD

**Issue by jfs89** [matomo-org/looker-studio-connector#62]
I'm finding it hard to get a total conversion figure for each channel?

I can see all the individual goals by channel but not a total conversion figure. I also can't just add them all together in a calculated field in Looker Studio as there is quotation marks in individual conversion metrics so this get treat as literal strings. I have tried to escape them with '\' to no avail. 

Any help would be much appreciated.

**Comment by diosmosis** [comment]
Hi @jfs89, there should be a conversions metric there, but it seems a bug in the Matomo API is keeping it from being displayed. I'll see if it can be fixed quickly, but when fixed, it will require an update to the Matomo you are connecting to for the metric to become available. Though I *might* be able to add something temporary to the connector for this case...

**Comment by jfs89** [comment]
Thanks for your help. Has this now been pushed live? As I still can't see a total conversion metric in the channels report.

**Comment by diosmosis** [comment]
It has not been deployed yet. When it is this issue will be closed.

**Comment by diosmosis** [comment]
This has been deployed, but you may need to reconnect reports for which you want to see overall conversions.
